#!/usr/bin/env bash

# Evaluate model on Metacentrum infrastructure
# Arguments: git branch, model name, walltime

# Builds on: https://github.com/bakajstep/KNN_Project2024/blob/main/metacetrum_scripts/test.sh
# Which in turn builds on: https://github.com/roman-janik/diploma_thesis_program/blob/main/ner/start_training_ner.sh

GIT_BRANCH="${1:-main}"
MODEL=$2
WALLTIME=$3

# -v list of environment variables to be given to the job
qsub -v GIT_BRANCH="$GIT_BRANCH",KNN_MODEL="$MODEL" -l walltime="$WALLTIME" ./"$(dirname "$0")"/evaluate_job
