#!/usr/bin/env bash

# Evaluate model on Metacentrum infrastructure
# Arguments: git branch, model name, walltime

# Builds on: https://github.com/bakajstep/KNN_Project2024/blob/main/metacetrum_scripts/test.sh
# Which in turn builds on: https://github.com/roman-janik/diploma_thesis_program/blob/main/ner/start_training_ner.sh

GIT_BRANCH="${1:-main}"
WALLTIME="$2"
DATASET_DIR="$3"
MODEL="$4"
MODEL_FILENAME="$5"

ARG_STRING=GIT_BRANCH="$GIT_BRANCH",KNN_MODEL="$MODEL",KNN_DATASET_DIR="$DATASET_DIR"

if [ -n "$MODEL_FILENAME" ]; then
    ARG_STRING+=,KNN_MODEL_FILENAME="$MODEL_FILENAME"
fi

# -v list of environment variables to be given to the job
qsub -v "$ARG_STRING" -l walltime="$WALLTIME" ./"$(dirname "$0")"/evaluate_job
