#!/usr/bin/env bash

# Train model on Metacentrum infrastructure
# Arguments: git branch, model name, walltime

# Builds on: https://github.com/bakajstep/KNN_Project2024/blob/main/metacetrum_scripts/test.sh
# Which in turn builds on: https://github.com/roman-janik/diploma_thesis_program/blob/main/ner/start_training_ner.sh

GIT_BRANCH="${1:-main}"
WALLTIME="$2"
KNN_BATCH_SIZE="$3"
KNN_DATASET_DIR="$4"

# -v list of environment variables to be given to the job
qsub -v GIT_BRANCH="$GIT_BRANCH",KNN_BATCH_SIZE="$KNN_BATCH_SIZE",KNN_DATASET_DIR="$KNN_DATASET_DIR",KNN_DOWNLOAD_DATASET=True \
  -l walltime="$WALLTIME" ./"$(dirname "$0")"/train_model_job
